<a href="https://colab.research.google.com/github/yongzhiqu/ME-5166-6166-MBSE-U-Utah/blob/main/python_notebook_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



> Indented block
Python is an Object Oriented Programming language. Why use OOP?
Object Oriented Programming (OOP) is one of the most widely used programming paradigm
​
Why is it extensively used?
Well suited for building trivial and complex applications
Allows re-use of code thereby increasing productivity
New features can be easily built into the existing code
Reduced production cost and maintenance cost
​
Common programming languages used for OOP include C++, Java, and C#


In [ ]:
def print_helloWorld():

    myString = 'Hello World!'
    print(myString)

def print_string(mySrg):
    print(mySrg)


In [ ]:
print_helloWorld()

Hello World!


In [ ]:
string_1 = 'Yongzhi'
print_string(string_1)

Yongzhi


how python pass values

In [1]:
the_world_is_flat = True

if the_world_is_flat:
    print("Be careful not to fall off!")

Be careful not to fall off!


In [2]:
the_world_is_flat = False

if the_world_is_flat:
    print("Be careful not to fall off!")

In [4]:
a = 3
b = 5
c = a + b
print(c)

squares = [1, 4, 9, 16, 25]

# The following codes index the same element
print(len(squares))
print(squares[4])

print(squares[len(squares)-1])
print(squares[-1])




8
5
25
25
25


In [8]:
import numpy as np
squares1 = squares + [36, 49, 64, 81, 100]
squares1

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [14]:
square2 = np.array(squares)
square3 = np.array([36, 49, 64, 81, 100])
square4 = square2+square3
print(square4)

[ 37  53  73  97 125]


In [16]:
square5 = square2*square3
print(square5)

[  36  196  576 1296 2500]


In [20]:
b=[]
for j in squares:
    b.append(j)
b

[1, 4, 9, 16, 25]

In [ ]:
d=[]
for number in squares:
    d.append(number)

print(d)

[1, 4, 9, 16, 25]


In [21]:
import numpy as np
squares2 = np.array([1, 4, 9, 16, 25])
print(squares2)
squares3 = np.array([36, 49, 64, 81, 100])
print(squares3)

squares4 = squares2+squares3
print(squares4)

[ 1  4  9 16 25]
[ 36  49  64  81 100]
[ 37  53  73  97 125]


In [ ]:
cubes = [1, 8, 27, 65, 125]

In [ ]:
import numpy as np #Features
x = np.array([[2, 1834, 1],[3, 1534, 2],[2, 962, 3]])# Target or Price
y = [8500, 9600, 258800]
y = np.array(y)
print(y+y)

[ 17000  19200 517600]


In [22]:
A = [[1, 4, 5, 12],
     [-5, 8, 9, 0],
     [-6, 7, 11, 19]] # This defines a list

print("A =", A)
print("A[0] =", A[0])      # 1st row
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row
print("A[0][-2] =", A[0][-2])   # Last element of 1st Row
print("thirdRow = ", A[1])
column = [];        # empty list
for element in A:
    column.append(element[2])

print("3rd column =", column)

print(A[:,2])
# this gives you an error, becuase list indices must be integers or slices, not tuple
# however, this will work for numpy array, because numpy array (numpy library) has everything of python list and its ownextra.

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
A[0] = [1, 4, 5, 12]
A[1][2] = 9
A[0][-2] = 5
thirdRow =  [-5, 8, 9, 0]
3rd column = [5, 9, 11]


TypeError: ignored

In [24]:
A = np.array([[1, 4, 5, 12],
              [-5, 8, 9, 0],
              [-6, 7, 11, 19]]) # this defines a numpy array

print("A =", A)
print("A[0] =", A[0])      # 2nd row
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row
print("A[0][-2] =", A[0][-2])   # Last element of 1st Row
print("thirdRow = ", A[1])
column = [];        # empty list
for element in A:
    column.append(element[2])
print("3rd column =", column)

print(A[:,2]) # this works for array, but not for list because numpy library has everything of python list and its own extra

A = [[ 1  4  5 12]
 [-5  8  9  0]
 [-6  7 11 19]]
A[0] = [ 1  4  5 12]
A[1][2] = 9
A[0][-2] = 5
thirdRow =  [-5  8  9  0]
3rd column = [5, 9, 11]
[ 5  9 11]


In [25]:
A = [[[1, 4, 5, 12],
     [-5, 8, 9, 0],
     [-6, 7, 11, 19]],[[1, 4, 5, 12],
     [-5, 8, 9, 0],
     [-6, 7, 11, 19]]]
     # this is to show you how you can create multiple dimensional list
     # in class, my code do not have the numpy.array() conversion, it is not a matrix but a high dimensional list

# we can do this in numpy
A_1 = np.array([[[1, 4, 5, 12],
     [-5, 8, 9, 0],
     [-6, 7, 11, 19]],[[1, 4, 5, 12],
     [-5, 8, 9, 0],
     [-6, 7, 11, 19]]])
# now A_1 is a tensor (a high dimensional matrix)

print("A_1 =", A_1)
print("A_1[0] =", A_1[0])      # 2nd row
print("A_1[1][2] =", A_1[1][2])   # 3rd element of 2nd row
print("A_1[0][-2] =", A_1[0][-2])   # Last element of 1st Row
print("thirdRow = ", A_1[1])
column = [];        # empty list
for element in A_1:
    column.append(element[2])
print("3rd column =", column)


A_1 = [[[ 1  4  5 12]
  [-5  8  9  0]
  [-6  7 11 19]]

 [[ 1  4  5 12]
  [-5  8  9  0]
  [-6  7 11 19]]]
A_1[0] = [[ 1  4  5 12]
 [-5  8  9  0]
 [-6  7 11 19]]
A_1[1][2] = [-6  7 11 19]
A_1[0][-2] = [-5  8  9  0]
thirdRow =  [[ 1  4  5 12]
 [-5  8  9  0]
 [-6  7 11 19]]
3rd column = [array([-6,  7, 11, 19]), array([-6,  7, 11, 19])]


In [33]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
z = np.array([2,3])
y = np.linalg.inv(x)
print (x)
# print (y)
#print (x*y)
print (x*z)
print(np.dot(x, z))
print(np.matmul(x, z))
#w=np.dot(x,y)
# print(w)

print ('**********I am the separation line ************')
z = np.matmul(x,y)
print(z)




[[1. 2.]
 [3. 4.]]
[[ 2.  6.]
 [ 6. 12.]]
[ 8. 18.]
[ 8. 18.]
**********I am the separation line ************
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float32)
y = np.linalg.inv(x)
print (x)
print (y)
print (x*y)
w=np.dot(x,y)
print(w)

print ('**********I am the separation line ************')
z = np.matmul(x,y)
print(z)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   2. ]
 [ 4.5 -2. ]]
[[1. 0.]
 [0. 1.]]
**********I am the separation line ************
[[1. 0.]
 [0. 1.]]


In [ ]:
x = np.arange(10)
print(x)


for k in range(10):
     print(k+5)

[0 1 2 3 4 5 6 7 8 9]
5
6
7
8
9
10
11
12
13
14


In [ ]:
A = [[1, 4, 5], [-5, 8, 9], [-6, 7, 11]]
A = np.array (A)
transpose_A = A.transpose()
transpose_A2 = np.transpose(A)

print (transpose_A)

print (transpose_A2)

[[ 1 -5 -6]
 [ 4  8  7]
 [ 5  9 11]]
[[ 1 -5 -6]
 [ 4  8  7]
 [ 5  9 11]]


In [ ]:
AA = np.array([[1,2],[3,4]])
b = np.array([2,3])
print(AA*b) # elmentwise multiply. this is not matix multiply
print(np.dot(AA, b)) # dot multiply
print(np.matmul(AA, b)) # innner product, more general, recommended
print(AA@b)

[[ 2  6]
 [ 6 12]]
[ 8 18]
[ 8 18]
[ 8 18]


In [34]:
A = np.random.rand(3,2)
print(A)
print(A.T)

[[0.82489119 0.66283745]
 [0.82949967 0.60342001]
 [0.74942002 0.49045737]]
[[0.82489119 0.82949967 0.74942002]
 [0.66283745 0.60342001 0.49045737]]


3x + 4y - 2z = 5

x - y -z = 2

y + 3z = 3

In [ ]:
import numpy as np
A = np.array([[3, 4, -2], [1, -1, -1], [0, 1,3]])
b = np.array([5, 2, 3])

In [ ]:
xyz = np.linalg.inv(A)*b # wrong
print('xyz=', xyz)
xyz2 = np.matmul(np.linalg.inv(A), b)
print('xyz2=',xyz2)

# verify the answer
print(np.matmul(A,xyz2))

xyz= [[ 0.5   1.4   0.9 ]
 [ 0.75 -0.9  -0.15]
 [-0.25  0.3   1.05]]
xyz2= [ 2.8 -0.3  1.1]
[5. 2. 3.]


In [ ]:
eig_A=np.linalg.eig(A)
eig_A

(array([13.59373746,  5.03209301,  1.37416954]),
 array([[ 0.45145779,  0.83661458,  0.10258363],
        [ 0.62348353,  0.44632316, -0.77299039],
        [ 0.63832135,  0.31760303,  0.62606905]]))