<a href="https://colab.research.google.com/github/yongzhiqu/ME-5166-6166-MBSE-U-Utah/blob/main/python_Nupmy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A = [[1, 4, 5], [-5, 8, 9], [-6, 7, 11]]
A = np.array (A)
transpose_A = A.transpose()

transpose_A2 = np.transpose(A)

print (transpose_A)

print (transpose_A2)

[[ 1 -5 -6]
 [ 4  8  7]
 [ 5  9 11]]
[[ 1 -5 -6]
 [ 4  8  7]
 [ 5  9 11]]


In [ ]:
eig_A=np.linalg.eig(A)
eig_A

(array([13.59373746,  5.03209301,  1.37416954]),
 array([[ 0.45145779,  0.83661458,  0.10258363],
        [ 0.62348353,  0.44632316, -0.77299039],
        [ 0.63832135,  0.31760303,  0.62606905]]))

In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.66590177 0.58281732]
 [0.10757082 0.74598647]]


Note that the numpy library does not make a distinction between column and row vectors. Matrix multiplication can be performed using the following syntax:

In [ ]:
result = my_array.dot(my_vector)
print(result)

[ 5 11]


Or, equivalently, with the following syntax:

In [ ]:
result = np.dot(my_array,my_vector)
print(result)

[ 5 11]


Note that the multiplication operator performs an element-wise matrix opperation rather than a matrix multiplication. Because of this, the following is not equivalent to a matrix multiplication.

In [ ]:
result = my_array*my_vector
print(result)

[[1 4]
 [3 8]]


In [ ]:
x = np.array([[1,2],[3,4]])
x.astype(float)
y = np.linalg.inv(x)
y.astype(float)
print (x)
print (y)
print (x*y)
w=np.dot(x,y)
print(w)

print ('**********I am the separation line ************')
z = np.matmul(x,y)
print(z)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   2. ]
 [ 4.5 -2. ]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
**********I am the separation line ************
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


A numpy tutorial can be found [here](http://docs.scipy.org/doc/numpy/user/quickstart.html). If you're familiar with Matlab, a numpy tutorial for Matlab users is available [here](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html).

In [ ]:
import numpy as np
input = np.array([[3,5,6], [1,2,2], [1,6,-2]])
output = np.array([10,13,2])
print(input)
print(output)

[[ 3  5  6]
 [ 1  2  2]
 [ 1  6 -2]]
[10 13  2]


In [ ]:
coff=np.matmul(np.linalg.inv(input),output)
coff

array([-108.5 ,   29.  ,   31.75])

In [ ]:
predictY = np.matmul(input,coff)
predictY

array([10., 13.,  2.])

In [ ]:
input2 = np.array([[3,4,6],[1,2,3],[4, -4, 10]])
input2


array([[ 3,  4,  6],
       [ 1,  2,  3],
       [ 4, -4, 10]])

In [ ]:
output2 = np.matmul(input2,coff)
output2

array([ -19.  ,   44.75, -232.5 ])